---
title: "Lista - Planejamento De Experimentos"
output: pdf_document
---

```{r}
knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE)
```

# Questão 1

```{r}
library(tidyr)

# Criando a combinação de cada fator três vezes 
A <- rep(c("A0", "A1"), each = 6) # each: repete cada item
B <- rep(c("B0", "B1", "B0", "B1"), each = 3) # times: repete todo o vetor duas vezes

A;B

peso <- c(1.30, 1.19, 1.08, # Primeira combinação
          1.26, 1.21, 1.19, # Segunda combinação
          1.05, 1.00, 1.05, # Terceira combinação
          1.52, 1.56, 1.55  # Quarta combinação
          ) 

modelo <- lm(peso ~ A * B)

resultado_anova <- aov(modelo) # Anova

summary(resultado_anova) # Sumário
```


```{r}
library(FrF2)

planej = FrF2(nfactors = 2,
nruns = 2^2,
factor.names =c("B", "A"), # Invertendo a ordem para se adequar a tabela 
replications = 3,
randomize = FALSE)

rendimento = c(1.30,1.26,1.05,1.52,
               1.19,1.21,1.00,1.56,
               1.08,1.19,1.05,1.55)

planej = add.response(planej, rendimento)
knitr::kable(planej)
```

```{r}
modelo <- lm(rendimento ~ A * B, data =
planej)

anova <-  aov(modelo)

summary(anova)
```

```{r}
shapiro.test(modelo$residuals)
```

```{r}
with(planej, bartlett.test(anova$residuals~A))
with(planej, bartlett.test(anova$residuals~B))
tratamentos<-rep(c(paste("T",1:4)),e=3)
with(planej, bartlett.test(anova$residuals~tratamentos))
```

```{r}
lmtest::dwtest(anova)
```

```{r}
library(ExpDes.pt)

with(planej, fat2.dic(A,B, rendimento, mcomp="tukey", fac.names = c("A","B")))
```

